# Generated by Django 5.2.6 on 2025-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
