# Generated by Django 5.2.6 on 2025-09-22 10:17

import django.core.validators
import django.db.models.deletion
import myapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetyguide',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Safety Guide', 'verbose_name_plural': 'Safety Guides'},
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_safety_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safetyguide',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Legacy attachment data - use SafetyGuideAttachment model for new files', null=True),
        ),
        migrations.AlterField(
            model_name='safetyguide',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_safety_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safetyguide',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the safety guide (JPG, PNG, GIF, WebP)', null=True, upload_to=myapp.models.safety_guide_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.CreateModel(
            name='SafetyGuideAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=myapp.models.safety_guide_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'aac', 'zip', 'rar', '7z', 'tar', 'gz'])])),
                ('name', models.CharField(help_text='Display name for the attachment', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('file_type', models.CharField(editable=False, max_length=50)),
                ('file_size', models.PositiveIntegerField(editable=False, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('safety_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='myapp.safetyguide')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Guide Attachment',
                'verbose_name_plural': 'Safety Guide Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
