# Generated by Django 5.2.6 on 2025-09-22 20:56

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_safetyguide_options_safetyguide_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyguide',
            name='attachments',
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_1',
            field=models.FileField(blank=True, help_text='First attachment file', null=True, upload_to=myapp.models.safety_guide_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'aac', 'zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_1_description',
            field=models.TextField(blank=True, help_text='Description for attachment 1'),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_1_name',
            field=models.CharField(blank=True, help_text='Display name for attachment 1', max_length=255),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.safety_guide_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'aac', 'zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.safety_guide_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'aac', 'zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_4',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.safety_guide_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'aac', 'zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_4_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_5',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.safety_guide_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'aac', 'zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_5_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='attachment_5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='safetyguide',
            name='legacy_attachments',
            field=models.JSONField(blank=True, default=list, help_text='Legacy attachment data from previous version', null=True),
        ),
        migrations.DeleteModel(
            name='SafetyGuideAttachment',
        ),
    ]
