# Generated by Django 5.2.6 on 2025-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chatroom_options_chatroom_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('admin', 'Administrator'), ('village', 'Village'), ('sector', 'Sector'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], default='citizen', max_length=20),
        ),
    ]
