# Generated by Django 5.2.6 on 2025-10-14 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLevelResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_level', models.CharField(choices=[('village', 'Village'), ('sector', 'Sector'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], help_text='Administrative level at which this action was taken', max_length=20)),
                ('action_type', models.CharField(choices=[('received', 'Received'), ('assessed', 'Assessed'), ('in_progress', 'In Progress'), ('action_taken', 'Action Taken'), ('escalated', 'Escalated to Next Level'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
                ('notes', models.TextField(help_text='What was done at this level')),
                ('resources_deployed', models.TextField(blank=True, help_text='Resources, personnel, or equipment deployed')),
                ('outcome', models.TextField(blank=True, help_text='Result of actions taken at this level')),
                ('escalation_needed', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True, help_text='Why this needs to go to the next level')),
                ('attachments', models.JSONField(blank=True, help_text='Photos/documents of response actions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='incident_media/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='images',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='videos',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='current_level',
            field=models.CharField(choices=[('village', 'Village'), ('sector', 'Sector'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], default='village', help_text='Current administrative level handling this incident', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='needs_escalation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Current user assigned to handle this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Minimal')], default=3),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='submitted', max_length=15),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status', '-created_at'], name='myapp_incid_status_dd4095_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['current_level', 'status'], name='myapp_incid_current_1c175b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['assigned_to', '-created_at'], name='myapp_incid_assigne_b55389_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['location', '-created_at'], name='myapp_incid_locatio_1ead99_idx'),
        ),
        migrations.AddField(
            model_name='incidentlevelresponse',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_responses', to='myapp.incidentreport'),
        ),
        migrations.AddField(
            model_name='incidentlevelresponse',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentmedia',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='myapp.incidentreport'),
        ),
        migrations.AddField(
            model_name='incidentmedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incidentlevelresponse',
            index=models.Index(fields=['incident', 'admin_level', '-created_at'], name='myapp_incid_inciden_a77d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentlevelresponse',
            index=models.Index(fields=['responder', '-created_at'], name='myapp_incid_respond_29eb65_idx'),
        ),
    ]
