# Generated by Django 5.2.6 on 2025-12-20 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlevelresponse',
            name='feedback_for_lower_levels',
            field=models.TextField(blank=True, help_text='Feedback or updates for lower administrative levels'),
        ),
        migrations.AddField(
            model_name='incidentlevelresponse',
            name='feedback_for_reporter',
            field=models.TextField(blank=True, help_text='Feedback or updates for the original reporter'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.incidentreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
