# Generated by Django 6.0 on 2026-01-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_incidentlevelresponse_feedback_for_lower_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('admin', 'Administrator'), ('village', 'Village'), ('cell', 'Cell'), ('sector', 'Sector'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], default='citizen', max_length=20),
        ),
    ]
