# Generated by Django 6.0 on 2026-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentlevelresponse',
            name='admin_level',
            field=models.CharField(choices=[('village', 'Village'), ('cell', 'Cell'), ('sector', 'Sector'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], help_text='Administrative level at which this action was taken', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='current_level',
            field=models.CharField(choices=[('village', 'Village'), ('cell', 'Cell'), ('sector', 'Sector'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], default='village', help_text='Current administrative level handling this incident', max_length=20),
        ),
    ]
