# Generated by Django 6.0 on 2026-01-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_incidentlevelresponse_admin_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
    ]
